/**
 * Rule Engine - Matches requests against interception rules
 *
 * This module is responsible for:
 * - Storing and managing interception rules
 * - Matching URLs against rule patterns (exact, wildcard, regex, contains)
 *
 * A rule describes how a matched request should be mocked. The actual mock
 * response (body, headers, status code) is generated by the interceptor; this
 * engine only decides *which* rule applies to a given request.
 *
 * @module RuleEngine
 */

/**
 * @typedef {Object} Rule
 * @property {string} id - Unique rule identifier
 * @property {string} name - Human-readable rule name
 * @property {string} urlPattern - URL pattern to match against
 * @property {('exact'|'wildcard'|'regex'|'contains')} matchType - Type of URL matching
 * @property {string[]} [methods] - HTTP methods to match (GET, POST, etc.)
 * @property {boolean} enabled - Whether the rule is active
 * @property {('replace')} [modifyType] - Type of mock body (only full-body replace is supported)
 * @property {Object} [modification] - Mock body configuration
 * @property {HeaderModification[]} [modifyHeaders] - Header modifications applied to the mock
 * @property {number} [modifyStatusCode] - Mock response status code
 * @property {number} [delay] - Response delay in milliseconds
 * @property {number} [priority] - Match priority; higher wins when several rules match (default 0)
 */

/**
 * @typedef {Object} HeaderModification
 * @property {string} name - Header name
 * @property {string} value - Header value
 * @property {('add'|'set'|'remove')} action - Modification action
 */

import { safeCompileRegex } from '../shared/regex.js';
import { compileWildcard } from '../shared/url-matching.js';
import { debug } from '../shared/debug.js';

export class RuleEngine {
  constructor() {
    /** @type {Rule[]} */
    this.rules = [];
    /** @type {Map<string, RegExp>} Pre-compiled regex patterns for performance */
    this.compiledPatterns = new Map();
  }

  /**
   * Load rules into the engine
   * @param {Rule[]} rules - Array of rules to load
   */
  setRules(rules) {
    // Validate input is an array
    if (!Array.isArray(rules)) {
      debug.error('setRules: rules must be an array, received:', typeof rules);
      this.rules = [];
      return;
    }
    // Filter to only enabled rules with valid structure
    this.rules = rules.filter(rule => rule && typeof rule === 'object' && rule.enabled);
    this.compilePatterns();
    debug.log(`Rule engine loaded ${this.rules.length} enabled rules`);
  }

  /**
   * Pre-compile regex patterns for better performance
   * @private
   */
  compilePatterns() {
    this.compiledPatterns.clear();
    this.rules.forEach(rule => {
      if (rule.matchType === 'regex') {
        const compiled = safeCompileRegex(rule.urlPattern);
        if (compiled) {
          this.compiledPatterns.set(rule.id, compiled);
        } else {
          debug.error(`Skipping unsafe/invalid regex for rule ${rule.id}`);
        }
      } else if (rule.matchType === 'wildcard') {
        const compiled = compileWildcard(rule.urlPattern);
        if (compiled) this.compiledPatterns.set(rule.id, compiled);
      }
    });
  }

  /**
   * Check if a URL matches a given pattern
   * @param {string} url - The URL to test
   * @param {string} pattern - The pattern to match against
   * @param {('exact'|'wildcard'|'regex'|'contains')} matchType - Type of matching
   * @returns {boolean} Whether the URL matches
   */
  matchUrl(url, pattern, matchType) {
    switch (matchType) {
      case 'exact':
        return url === pattern;

      case 'wildcard': {
        const compiled = compileWildcard(pattern);
        return compiled ? compiled.test(url) : false;
      }

      case 'regex': {
        const regex = safeCompileRegex(pattern);
        return regex ? regex.test(url) : false;
      }

      case 'contains':
        return url.includes(pattern);

      default:
        return false;
    }
  }

  /**
   * Match URL against a rule using pre-compiled patterns where available
   * @param {string} url - The URL to test
   * @param {Rule} rule - The rule to match against
   * @returns {boolean} Whether the URL matches
   * @private
   */
  matchUrlForRule(url, rule) {
    const compiled = this.compiledPatterns.get(rule.id);
    if (compiled) {
      return compiled.test(url);
    }
    // 'regex' and 'wildcard' are always pre-compiled in compilePatterns(), so a
    // missing entry means compilation was *rejected* — the rule can never match.
    // Falling through would recompile it (and re-log the rejection) on every
    // single request, only to arrive at the same false.
    if (rule.matchType === 'regex' || rule.matchType === 'wildcard') {
      return false;
    }
    // Fallback for exact/contains (no pre-compilation needed)
    return this.matchUrl(url, rule.urlPattern, rule.matchType);
  }

  /**
   * Find all rules that match a given URL and HTTP method
   * @param {string} url - The request URL
   * @param {string} [method='GET'] - The HTTP method
   * @returns {Rule[]} Array of matching rules (first match has highest priority)
   */
  findMatchingRules(url, method = 'GET') {
    const matchingRules = [];

    for (const rule of this.rules) {
      // Check if method matches
      if (rule.methods && rule.methods.length > 0) {
        if (!rule.methods.includes(method)) {
          continue;
        }
      }

      // Check if URL matches
      if (this.matchUrlForRule(url, rule)) {
        matchingRules.push(rule);
      }
    }

    // Highest priority wins. Array.prototype.sort is stable, so equal
    // priorities keep insertion order — existing rules (all default 0) behave
    // exactly as before this field existed.
    matchingRules.sort((a, b) => (b.priority || 0) - (a.priority || 0));

    return matchingRules;
  }
}
